basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: API для e-commerce платформи з управлінням продуктами, кошиком та замовленнями
  title: E-Commerce API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
